<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "systemplates_to_files"
 *
 * Auto generated by Extension Builder 2021-04-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sys_templates to Files',
    'description' => 'write database sys_template records as *.typoscript files to an extension',
    'category' => 'plugin',
    'author' => 'Sven Jürgens',
    'author_email' => 't3@blue-side.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.3',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.30-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
